vim25/*: Fix staticcheck issues
See,
$ staticcheck ./vim25/...
vim25/client.go:70:13: should use !strings.Contains(c.Namespace, ":") instead (S1003)
vim25/progress/reader.go:161:24: should use time.Since instead of time.Now().Sub (S1012)
vim25/progress/reader_test.go:75:2: this value of q is never used (SA4006)
vim25/progress/reader_test.go:82:2: this value of q is never used (SA4006)
vim25/retry_test.go:76:3: should merge variable declaration with assignment on next line (S1021)
vim25/retry_test.go:81:23: do not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use (SA1012)
vim25/soap/client.go:348:25: error strings should not be capitalized (ST1005)
vim25/soap/debug.go:86:2: should merge variable declaration with assignment on next line (S1021)
vim25/soap/debug.go:107:2: should merge variable declaration with assignment on next line (S1021)